### ISSUE TITLE
Unable to install queen via npm in OSX 10.7.4 - "command not found"

### ISSUE THREAD

**Issue by josue** [unsetbit/queen#1]
josue@~/Sites $ sudo npm install -g queen
npm http GET https://registry.npmjs.org/queen
...............
npm http 304 https://registry.npmjs.org/commander

> ws@0.4.25 install /usr/local/share/npm/lib/node_modules/queen/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
/usr/local/share/npm/bin/queen -> /usr/local/share/npm/lib/node_modules/queen/bin/queen
queen@0.4.0 /usr/local/share/npm/lib/node_modules/queen
├── node-uuid@1.3.3
├── its@1.0.0
├── commander@1.0.5 (keypress@0.1.0)
├── useragent@1.1.0 (yamlparser@0.0.2, semver@1.0.14, request@2.9.202)
├── queen-monitor-plugin@0.1.0
├── queen-remote@0.3.1 (json-over-tcp@0.3.1, commander@1.1.1)
├── queen-populator-plugin@0.2.0 (browserstack@0.2.0, wd@0.0.28)
├── express@3.0.6 (methods@0.0.1, fresh@0.1.0, range-parser@0.0.4, cookie-signature@0.0.1, buffer-crc32@0.1.1, cookie@0.0.5, commander@0.6.1, debug@0.7.0, mkdirp@0.3.3, send@0.1.0, connect@2.7.2)
└── socket.io@0.9.13 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.11)

josue@~/Sites $ queen
-bash: queen: command not found

**Comment by unsetbit** [comment]
Could you check to see if "/usr/local/share/npm/bin" in your $PATH? You can check by typing `echo $PATH`

 If not, you'll have to add it: by adding this to ~/.bashrc, and then reopening your terminal window:
`export PATH="/usr/local/share/npm/bin:$PATH"`

**Comment by josue** [comment]
That was the issue, missing 'npm/bin' in $PATH. Thanks.
