### ISSUE TITLE
workerProvider on "available" doesn't appear to fire

### ISSUE THREAD

**Issue by jcreamer898** [unsetbit/queen#12]
In the following code, I'm trying to listen for a worker provider's `available` event, but it never seems to fire.

``` js
var options = {
            captureHost : "localhost:9000",
            debug: function( str ) {
                console.log("debug..." + str )
            },
            log: function(str) {
                console.log("log..." + str )
            }
        };

        options.callback = function(instance) {
            open(instance.captureUrl);

            grunt.log.write(
                util.format("queen is now running on: %s", instance.captureUrl)
            );

            instance.on("workerProvider", function( provider ) {

                provider.on("available", function() {
                    grunt.log.write( "available\n" );
                    done( true );
                });

                console.log(provider);
            });
        };

        queen(options);
```

Am I missing something? 

Thanks!

**Comment by unsetbit** [comment]
Availability is an indicator of the capacity a provider has to create workers. Currently when a provider connects to Queen it's assumed it has the capacity to start workers immediately.

The "workerProvider" event is emitted once a connection has registered itself, so you can assume the providers you receive through that event are available.

Providers become unavailable once their worker pool (the amount of iframes it can run concurrently) is exhausted, and they will fire the "available" event once it has the capacity to start new workers again.

**Comment by jcreamer898** [comment]
Thank you for the information!
