### ISSUE TITLE
problem on connection

### ISSUE THREAD

**Issue by francescoagati** [unsetbit/queen#15]
with node 0.10 i have this error during testing

[Queen Remote Server] Connection error by 127.0.0.1:53638: Error: read ECONNRESET

**Comment by unsetbit** [comment]
Hi Frances, 

Unfortunately I can't duplicate this. I'm running node 0.10.26 and am able to run the tests along with runtime sample (`queen -c localhost:9300 http://queenjs.com/server-example.js`) without errors. 

If you'd still like me to look into this, could you please provide more instructions on how I could reproduce this? I'm going to close this issue until then.
