### ISSUE TITLE
Maximum call stack size exceeded (buffer.js:242)

### ISSUE THREAD

**Issue by purplematter** [unsetbit/queen#2]
Queen] Starting...
[Queen] Capturing browsers at http://localhost:9300/
[Queen] Initializing plugin: monitor
[Queen] Initializing plugin: populator
[Queen] Loading remote script: http://queenjs.com/server-example.js
[Queen] Executing remote script: http://queenjs.com/server-example.js

(i wait a few seconds without connecting any workers)

buffer.js:242
      this.parent = new SlowBuffer(this.length);
                    ^
RangeError: Maximum call stack size exceeded

---

OSX v10.7.5

**Comment by unsetbit** [comment]
I've seen this while using an older version of Node.js, which version are you using (`node --version`)?

**Comment by purplematter** [comment]
I was using v0.8.14, updating to v0.8.18 fixed the problem :) Thank you.

**Comment by unsetbit** [comment]
Great! I'll document this, so others don't have to go through it again :) Thanks for letting me know.
